### PR TITLE
Upgrade Pluxml to v5.8.3

### LINKED ISSUE #42: Upgrade to Pluxml 5.8.3
**Describe the bug**

Besoin de mettre à jour la version de Pluxml, actuellement en 5.7 alors que la 5.8.3 (2020/05/19) est disponible.

https://www.pluxml.org/download/changelog.txt

### PR DESCRIPTION
**Pull request by anto1ne**
## Problem
- Pluxml version is v5.7. Version 5.8.3 is nom available. Fix #42 

## Solution
- Upgrade to v5.8.3

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** :  

- **CI succeeded** : 
[Build Status/1/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/pluxml_ynh%20(antoine)/1/)

### CODE REVIEW

**Comment by anto1ne** [comment]
I think that the install script needs to be updated at line 224

https://github.com/YunoHost-Apps/pluxml_ynh/blob/0595d7bb0ffc224508c52ec5952125d77c4200e8/scripts/install#L224

**Comment by yalh76** [comment]
> 
> 
> [Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/pluxml_ynh%20(antoine)/1/)
> 
> 😞
> 
> I think that the install script needs to be updated at line 224
> 
> https://github.com/YunoHost-Apps/pluxml_ynh/blob/0595d7bb0ffc224508c52ec5952125d77c4200e8/scripts/install#L224

yep, it seems they changed things, I let you manage that ;)

**Comment by anto1ne** [comment]
[Build Status/3/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/pluxml_ynh%20(antoine)/3/)

ça progresse

```
Package linter:                  SUCCESS
Installation:                    SUCCESS
Deleting:                        SUCCESS
Installation in a sub path:      SUCCESS
Deleting from a sub path:        SUCCESS
Installation on the root:        SUCCESS
Deleting from root:              SUCCESS
Upgrade:                         FAIL
Installation in private mode:    SUCCESS
Installation in public mode:     SUCCESS
Multi-instance installations:    SUCCESS
Malformed path:                  Not evaluated.
Port already used:               Not evaluated.
Backup:                          SUCCESS
Restore:                         SUCCESS
Change URL:                      SUCCESS
Actions and config-panel:        Not evaluated.
Level of this application: 2 (Installable in all situations)
	   Level 1: 1
	   Level 2: 1
	   Level 3: 0
	   Level 4: 1
	   Level 5: 1
	   Level 6: 1
	   Level 7: 0
	   Level 8: 0
	   Level 9: 0
	   Level 10: 0
You can find the complete log of these tests in /home/CI_package_check/dev_CI/../package_check/Complete.log
```

à mon avis il faut regarder du coté du script d'upgrade et du dossier /update

**Comment by anto1ne** [comment]
@yalh76 , the upgrade script does not work, I am stuck with this command line

https://github.com/YunoHost-Apps/pluxml_ynh/blob/767b784a512d8790be8c15317947215f83712f87/scripts/upgrade#L119

I have also an issue when I update the commit in check_process

https://github.com/YunoHost-Apps/pluxml_ynh/blob/767b784a512d8790be8c15317947215f83712f87/check_process#L23

**Comment by yalh76** [comment]
L119 should be: `ynh_local_curl "/update/index.php" "submit=submit"`

In addition when putting a `read -p "key"` L120, I can go to the pluxml interface and try to manually do the upgrade clicking on the `Démarrer la mise à jour`, and it seems to not be abble to do the upgrade.

I think it's because the pluxml user doesn't own the `/var/www/$app` folder
The owning of the folder comes too late:
https://github.com/YunoHost-Apps/pluxml_ynh/blob/767b784a512d8790be8c15317947215f83712f87/scripts/upgrade#L137

**Comment by anto1ne** [comment]
thank you @yalh76 
you were right, I fixed the upgrade script, it should be working now 
[Build Status/15/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/pluxml_ynh%20(antoine)/15/)

**Pull request merged**
